/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCursoIndexRouteImport } from './routes/_authenticated/curso.index'
import { Route as AuthenticatedCursoModuloRouteImport } from './routes/_authenticated/curso.modulo.$moduloId'
import { Route as AuthenticatedCursoAulaRouteImport } from './routes/_authenticated/curso.aula.$aulaId'
import { Route as AuthenticatedQuestoesRouteImport } from './routes/_authenticated/questoes'
import { Route as AuthenticatedQuestoesIaRouteImport } from './routes/_authenticated/questoes.ia'
import { Route as AuthenticatedMateriaisRouteImport } from './routes/_authenticated/materiais'
import { Route as AuthenticatedFavoritosRouteImport } from './routes/_authenticated/favoritos'
import { Route as AuthenticatedIaRouteImport } from './routes/_authenticated/ia'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminModulosRouteImport } from './routes/_authenticated/admin.modulos'
import { Route as AuthenticatedAdminAulasIndexRouteImport } from './routes/_authenticated/admin.aulas.index'
import { Route as AuthenticatedAdminAulasNovaRouteImport } from './routes/_authenticated/admin.aulas.nova'
import { Route as AuthenticatedMeusCursosRouteImport } from './routes/_authenticated/meus-cursos'
import { Route as AuthenticatedAdminCursosIndexRouteImport } from './routes/_authenticated/admin.cursos.index'
import { Route as AuthenticatedAdminCursosNovoRouteImport } from './routes/_authenticated/admin.cursos.novo'
import { Route as AuthenticatedAdminAlunosRouteImport } from './routes/_authenticated/admin.alunos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCursoIndexRoute = AuthenticatedCursoIndexRouteImport.update({
  id: '/curso/',
  path: '/curso/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCursoModuloRoute = AuthenticatedCursoModuloRouteImport.update({
  id: '/curso/modulo/$moduloId',
  path: '/curso/modulo/$moduloId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCursoAulaRoute = AuthenticatedCursoAulaRouteImport.update({
  id: '/curso/aula/$aulaId',
  path: '/curso/aula/$aulaId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuestoesRoute = AuthenticatedQuestoesRouteImport.update({
  id: '/questoes',
  path: '/questoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuestoesIaRoute = AuthenticatedQuestoesIaRouteImport.update({
  id: '/questoes/ia',
  path: '/questoes/ia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMateriaisRoute = AuthenticatedMateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavoritosRoute = AuthenticatedFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIaRoute = AuthenticatedIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminModulosRoute = AuthenticatedAdminModulosRouteImport.update({
  id: '/admin/modulos',
  path: '/admin/modulos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAulasIndexRoute = AuthenticatedAdminAulasIndexRouteImport.update({
  id: '/admin/aulas/',
  path: '/admin/aulas/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAulasNovaRoute = AuthenticatedAdminAulasNovaRouteImport.update({
  id: '/admin/aulas/nova',
  path: '/admin/aulas/nova',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeusCursosRoute = AuthenticatedMeusCursosRouteImport.update({
  id: '/meus-cursos',
  path: '/meus-cursos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminCursosIndexRoute = AuthenticatedAdminCursosIndexRouteImport.update({
  id: '/admin/cursos/',
  path: '/admin/cursos/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminCursosNovoRoute = AuthenticatedAdminCursosNovoRouteImport.update({
  id: '/admin/cursos/novo',
  path: '/admin/cursos/novo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAlunosRoute = AuthenticatedAdminAlunosRouteImport.update({
  id: '/admin/alunos',
  path: '/admin/alunos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/curso/': typeof AuthenticatedCursoIndexRoute
  '/curso/modulo/$moduloId': typeof AuthenticatedCursoModuloRoute
  '/curso/aula/$aulaId': typeof AuthenticatedCursoAulaRoute
  '/questoes': typeof AuthenticatedQuestoesRoute
  '/questoes/ia': typeof AuthenticatedQuestoesIaRoute
  '/materiais': typeof AuthenticatedMateriaisRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/ia': typeof AuthenticatedIaRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/modulos': typeof AuthenticatedAdminModulosRoute
  '/admin/aulas/': typeof AuthenticatedAdminAulasIndexRoute
  '/admin/aulas/nova': typeof AuthenticatedAdminAulasNovaRoute
  '/meus-cursos': typeof AuthenticatedMeusCursosRoute
  '/admin/cursos/': typeof AuthenticatedAdminCursosIndexRoute
  '/admin/cursos/novo': typeof AuthenticatedAdminCursosNovoRoute
  '/admin/alunos': typeof AuthenticatedAdminAlunosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/curso': typeof AuthenticatedCursoIndexRoute
  '/curso/modulo/$moduloId': typeof AuthenticatedCursoModuloRoute
  '/curso/aula/$aulaId': typeof AuthenticatedCursoAulaRoute
  '/questoes': typeof AuthenticatedQuestoesRoute
  '/questoes/ia': typeof AuthenticatedQuestoesIaRoute
  '/materiais': typeof AuthenticatedMateriaisRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/ia': typeof AuthenticatedIaRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/modulos': typeof AuthenticatedAdminModulosRoute
  '/admin/aulas': typeof AuthenticatedAdminAulasIndexRoute
  '/admin/aulas/nova': typeof AuthenticatedAdminAulasNovaRoute
  '/meus-cursos': typeof AuthenticatedMeusCursosRoute
  '/admin/cursos': typeof AuthenticatedAdminCursosIndexRoute
  '/admin/cursos/novo': typeof AuthenticatedAdminCursosNovoRoute
  '/admin/alunos': typeof AuthenticatedAdminAlunosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/curso/': typeof AuthenticatedCursoIndexRoute
  '/_authenticated/curso/modulo/$moduloId': typeof AuthenticatedCursoModuloRoute
  '/_authenticated/curso/aula/$aulaId': typeof AuthenticatedCursoAulaRoute
  '/_authenticated/questoes': typeof AuthenticatedQuestoesRoute
  '/_authenticated/questoes/ia': typeof AuthenticatedQuestoesIaRoute
  '/_authenticated/materiais': typeof AuthenticatedMateriaisRoute
  '/_authenticated/favoritos': typeof AuthenticatedFavoritosRoute
  '/_authenticated/ia': typeof AuthenticatedIaRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/modulos': typeof AuthenticatedAdminModulosRoute
  '/_authenticated/admin/aulas/': typeof AuthenticatedAdminAulasIndexRoute
  '/_authenticated/admin/aulas/nova': typeof AuthenticatedAdminAulasNovaRoute
  '/_authenticated/meus-cursos': typeof AuthenticatedMeusCursosRoute
  '/_authenticated/admin/cursos/': typeof AuthenticatedAdminCursosIndexRoute
  '/_authenticated/admin/cursos/novo': typeof AuthenticatedAdminCursosNovoRoute
  '/_authenticated/admin/alunos': typeof AuthenticatedAdminAlunosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/login'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/dashboard'
    | '/curso/'
    | '/curso/modulo/$moduloId'
    | '/curso/aula/$aulaId'
    | '/questoes'
    | '/questoes/ia'
    | '/materiais'
    | '/favoritos'
    | '/ia'
    | '/admin/'
    | '/admin/modulos'
    | '/admin/aulas/'
    | '/admin/aulas/nova'
    | '/meus-cursos'
    | '/admin/cursos/'
    | '/admin/cursos/novo'
    | '/admin/alunos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/dashboard'
    | '/curso'
    | '/curso/modulo/$moduloId'
    | '/curso/aula/$aulaId'
    | '/questoes'
    | '/questoes/ia'
    | '/materiais'
    | '/favoritos'
    | '/ia'
    | '/admin'
    | '/admin/modulos'
    | '/admin/aulas'
    | '/admin/aulas/nova'
    | '/meus-cursos'
    | '/admin/cursos'
    | '/admin/cursos/novo'
    | '/admin/alunos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cadastro'
    | '/login'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/_authenticated/dashboard'
    | '/_authenticated/curso/'
    | '/_authenticated/curso/modulo/$moduloId'
    | '/_authenticated/curso/aula/$aulaId'
    | '/_authenticated/questoes'
    | '/_authenticated/questoes/ia'
    | '/_authenticated/materiais'
    | '/_authenticated/favoritos'
    | '/_authenticated/ia'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/modulos'
    | '/_authenticated/admin/aulas/'
    | '/_authenticated/admin/aulas/nova'
    | '/_authenticated/meus-cursos'
    | '/_authenticated/admin/cursos/'
    | '/_authenticated/admin/cursos/novo'
    | '/_authenticated/admin/alunos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/curso/': {
      id: '/_authenticated/curso/'
      path: '/curso'
      fullPath: '/curso/'
      preLoaderRoute: typeof AuthenticatedCursoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/curso/modulo/$moduloId': {
      id: '/_authenticated/curso/modulo/$moduloId'
      path: '/curso/modulo/$moduloId'
      fullPath: '/curso/modulo/$moduloId'
      preLoaderRoute: typeof AuthenticatedCursoModuloRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/curso/aula/$aulaId': {
      id: '/_authenticated/curso/aula/$aulaId'
      path: '/curso/aula/$aulaId'
      fullPath: '/curso/aula/$aulaId'
      preLoaderRoute: typeof AuthenticatedCursoAulaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/questoes': {
      id: '/_authenticated/questoes'
      path: '/questoes'
      fullPath: '/questoes'
      preLoaderRoute: typeof AuthenticatedQuestoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/questoes/ia': {
      id: '/_authenticated/questoes/ia'
      path: '/questoes/ia'
      fullPath: '/questoes/ia'
      preLoaderRoute: typeof AuthenticatedQuestoesIaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/materiais': {
      id: '/_authenticated/materiais'
      path: '/materiais'
      fullPath: '/materiais'
      preLoaderRoute: typeof AuthenticatedMateriaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favoritos': {
      id: '/_authenticated/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof AuthenticatedFavoritosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ia': {
      id: '/_authenticated/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof AuthenticatedIaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/modulos': {
      id: '/_authenticated/admin/modulos'
      path: '/admin/modulos'
      fullPath: '/admin/modulos'
      preLoaderRoute: typeof AuthenticatedAdminModulosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/aulas/': {
      id: '/_authenticated/admin/aulas/'
      path: '/admin/aulas'
      fullPath: '/admin/aulas/'
      preLoaderRoute: typeof AuthenticatedAdminAulasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/aulas/nova': {
      id: '/_authenticated/admin/aulas/nova'
      path: '/admin/aulas/nova'
      fullPath: '/admin/aulas/nova'
      preLoaderRoute: typeof AuthenticatedAdminAulasNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meus-cursos': {
      id: '/_authenticated/meus-cursos'
      path: '/meus-cursos'
      fullPath: '/meus-cursos'
      preLoaderRoute: typeof AuthenticatedMeusCursosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/cursos/': {
      id: '/_authenticated/admin/cursos/'
      path: '/admin/cursos'
      fullPath: '/admin/cursos/'
      preLoaderRoute: typeof AuthenticatedAdminCursosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/cursos/novo': {
      id: '/_authenticated/admin/cursos/novo'
      path: '/admin/cursos/novo'
      fullPath: '/admin/cursos/novo'
      preLoaderRoute: typeof AuthenticatedAdminCursosNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/alunos': {
      id: '/_authenticated/admin/alunos'
      path: '/admin/alunos'
      fullPath: '/admin/alunos'
      preLoaderRoute: typeof AuthenticatedAdminAlunosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedCursoIndexRoute: typeof AuthenticatedCursoIndexRoute
  AuthenticatedCursoModuloRoute: typeof AuthenticatedCursoModuloRoute
  AuthenticatedCursoAulaRoute: typeof AuthenticatedCursoAulaRoute
  AuthenticatedQuestoesRoute: typeof AuthenticatedQuestoesRoute
  AuthenticatedQuestoesIaRoute: typeof AuthenticatedQuestoesIaRoute
  AuthenticatedMateriaisRoute: typeof AuthenticatedMateriaisRoute
  AuthenticatedFavoritosRoute: typeof AuthenticatedFavoritosRoute
  AuthenticatedIaRoute: typeof AuthenticatedIaRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminModulosRoute: typeof AuthenticatedAdminModulosRoute
  AuthenticatedAdminAulasIndexRoute: typeof AuthenticatedAdminAulasIndexRoute
  AuthenticatedAdminAulasNovaRoute: typeof AuthenticatedAdminAulasNovaRoute
  AuthenticatedMeusCursosRoute: typeof AuthenticatedMeusCursosRoute
  AuthenticatedAdminCursosIndexRoute: typeof AuthenticatedAdminCursosIndexRoute
  AuthenticatedAdminCursosNovoRoute: typeof AuthenticatedAdminCursosNovoRoute
  AuthenticatedAdminAlunosRoute: typeof AuthenticatedAdminAlunosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedCursoIndexRoute: AuthenticatedCursoIndexRoute,
  AuthenticatedCursoModuloRoute: AuthenticatedCursoModuloRoute,
  AuthenticatedCursoAulaRoute: AuthenticatedCursoAulaRoute,
  AuthenticatedQuestoesRoute: AuthenticatedQuestoesRoute,
  AuthenticatedQuestoesIaRoute: AuthenticatedQuestoesIaRoute,
  AuthenticatedMateriaisRoute: AuthenticatedMateriaisRoute,
  AuthenticatedFavoritosRoute: AuthenticatedFavoritosRoute,
  AuthenticatedIaRoute: AuthenticatedIaRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminModulosRoute: AuthenticatedAdminModulosRoute,
  AuthenticatedAdminAulasIndexRoute: AuthenticatedAdminAulasIndexRoute,
  AuthenticatedAdminAulasNovaRoute: AuthenticatedAdminAulasNovaRoute,
  AuthenticatedMeusCursosRoute: AuthenticatedMeusCursosRoute,
  AuthenticatedAdminCursosIndexRoute: AuthenticatedAdminCursosIndexRoute,
  AuthenticatedAdminCursosNovoRoute: AuthenticatedAdminCursosNovoRoute,
  AuthenticatedAdminAlunosRoute: AuthenticatedAdminAlunosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
